src/protected/controllers/InformationController.php
<?php

class InformationController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','index','view','admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new InformationModel;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['InformationModel']))
		{
			$_POST['InformationModel']['create_date'] = date('Y-m-d H:i:s');
			$_POST['InformationModel']['update_date'] = date('Y-m-d H:i:s');
			if( $_POST['InformationModel']['display_date'] == '' )
			{
				$_POST['InformationModel']['display_date'] = date('Y-m-d H:i:s');
			}
			if( $_POST['InformationModel']['begin_date'] == '' )
			{
				$_POST['InformationModel']['begin_date'] = null;
			}
			if( $_POST['InformationModel']['end_date'] == '' )
			{
				$_POST['InformationModel']['end_date'] = null;
			}
			
			
			$model->attributes=$_POST['InformationModel'];
			if($model->save())
			{
				//$this->redirect(array('view','id'=>$model->id));
				$this->redirect( array('admin') );
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['InformationModel']))
		{
			$_POST['InformationModel']['update_date'] = date('Y-m-d H:i:s');
			if( $_POST['InformationModel']['display_date'] == '' )
			{
				$_POST['InformationModel']['display_date'] = date('Y-m-d H:i:s');
			}
			if( $_POST['InformationModel']['begin_date'] == '' )
			{
				$_POST['InformationModel']['begin_date'] = null;
			}
			if( $_POST['InformationModel']['end_date'] == '' )
			{
				$_POST['InformationModel']['end_date'] = null;
			}
			$model->attributes=$_POST['InformationModel'];
			if($model->save())
			{
				//$this->redirect(array('view','id'=>$model->id));
				$this->redirect( array('admin') );
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
		$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->redirect( array('admin') );
		return;
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new InformationModel('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['InformationModel']))
			$model->attributes=$_GET['InformationModel'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return InformationModel the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=InformationModel::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param InformationModel $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='information-model-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

src/protected/views/information/_form.php
<?php
/* @var $this InformationController */
/* @var $model InformationModel */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'information-model-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note"><span class="required">*</span>は必須</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row-fluid">
		<div class="span12">
			<?php echo $form->labelEx($model,'subject'); ?>
			<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>255, 'class'=> 'input-xxlarge' )); ?>
			<?php echo $form->error($model,'subject'); ?>
		</div>
	</div>
	
	
	<div class="row-fluid">
		<!--
		<div class="span6">
			<?php echo $form->labelEx($model,'create_date'); ?>
			<?php echo $form->textField($model,'create_date'); ?>
			<?php echo $form->error($model,'create_date'); ?>
		</div>
		<div class="span6">
			<?php echo $form->labelEx($model,'update_date'); ?>
			<?php echo $form->textField($model,'update_date'); ?>
			<?php echo $form->error($model,'update_date'); ?>
		</div>
		-->
		<div class="span6">
			<?php echo $form->labelEx($model,'display_date'); ?>
			<?php echo $form->textField($model,'display_date'); ?>
			<?php echo $form->error($model,'display_date'); ?>
		</div>
	</div>

	
	<div class="row-fluid">
		<div class="span4">
			<?php echo $form->labelEx($model,'begin_date'); ?>
			<?php echo $form->textField($model,'begin_date'); ?>
			<?php echo $form->error($model,'begin_date'); ?>
		</div>
		<div class="span4">
			<?php echo $form->labelEx($model,'end_date'); ?>
			<?php echo $form->textField($model,'end_date'); ?>
			<?php echo $form->error($model,'end_date'); ?>
		</div>
	</div>
	
	<div class="row-fluid">
		<div class="span4">
			<?php echo $form->labelEx($model,'open_status'); ?>
			<?php echo $form->dropDownList($model, 'open_status', InformationModel::getStatusList(), array() ); ?>
			<?php echo $form->error($model,'open_status'); ?>
		</div>
	</div>
	
	<div class="row-fluid">
		<div class="span12">
			<?php echo $form->labelEx($model,'description'); ?>
			<?php echo $form->textArea($model,'description',array( 'row' => 2, 'cols'=>50,'class'=> 'input-xxlarge')); ?>
			<?php echo $form->error($model,'description'); ?>
		</div>
	</div>
	
	<div class="row-fluid">
		<div class="span12">
			<?php echo $form->labelEx($model,'contents'); ?>
			<?php echo $form->textArea($model,'contents',array('rows'=>6, 'cols'=>50,'class'=> 'input-xxlarge cleditor')); ?>
			<?php echo $form->error($model,'contents'); ?>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span12">
			<div class="button-column buttons">
				<?php echo CHtml::submitButton(
						$model->isNewRecord ? '投稿！' : '編集！',
						array(
							'class' => 'btn btn-large btn-info'
						)
					); ?>
			</div>
		</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

src/protected/views/information/_search.php
<?php
/* @var $this InformationController */
/* @var $model InformationModel */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_date'); ?>
		<?php echo $form->textField($model,'create_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_date'); ?>
		<?php echo $form->textField($model,'update_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'display_date'); ?>
		<?php echo $form->textField($model,'display_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'begin_date'); ?>
		<?php echo $form->textField($model,'begin_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'end_date'); ?>
		<?php echo $form->textField($model,'end_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'open_status'); ?>
		<?php echo $form->textField($model,'open_status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'description'); ?>
		<?php echo $form->textField($model,'description',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'contents'); ?>
		<?php echo $form->textArea($model,'contents',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

src/protected/views/information/_view.php
<?php
/* @var $this InformationController */
/* @var $data InformationModel */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('subject')); ?>:</b>
	<?php echo CHtml::encode($data->subject); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_date')); ?>:</b>
	<?php echo CHtml::encode($data->create_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_date')); ?>:</b>
	<?php echo CHtml::encode($data->update_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('display_date')); ?>:</b>
	<?php echo CHtml::encode($data->display_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('begin_date')); ?>:</b>
	<?php echo CHtml::encode($data->begin_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('end_date')); ?>:</b>
	<?php echo CHtml::encode($data->end_date); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('open_status')); ?>:</b>
	<?php echo CHtml::encode($data->open_status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('contents')); ?>:</b>
	<?php echo CHtml::encode($data->contents); ?>
	<br />

	*/ ?>

</div>

src/protected/views/information/admin.php
<?php
/* @var $this InformationController */
/* @var $model InformationModel */

$this->breadcrumbs=array();

$this->menu=array();

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#information-model-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>お知らせ記事</h1>


<div class="search-form" style="">
<?php //$this->renderPartial('_search',array(
	//'model'=>$model,
//)); ?>
</div><!-- search-form -->


<!-- 操作パネル -->
<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-th"></i> 操作パネル</h2>
			<div class="box-icon">
			</div>
		</div>
		<div class="box-content">
			<div class="row-fluid">
				
				
				<?php echo CHtml::link(
						'新規登録',
						Yii::app()->createUrl('information/create'),
						array( 'class' => 'btn btn-large btn-primary')
					);
				?>
			</div>
		</div>
	</div>
</div>
<!-- /操作パネル -->


<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'information-model-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'display_date',
		'subject',
		'begin_date',
		'end_date',
		'description',
		array(
			'name' => 'open_status',
			'value' => function( $data ){
				$list = InformationModel::getStatusList();
				return $list[$data->open_status];
			}
		),
		array(
			'class'=>'CButtonColumn',
			'template' => '{update} {delete}'
		),
	),
)); ?>

src/protected/views/information/create.php
<?php
/* @var $this InformationController */
/* @var $model InformationModel */

$this->breadcrumbs=array();

$this->menu=array();
?>

<h1>お知らせ作成</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

src/protected/views/information/index.php
<?php
/* @var $this InformationController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Information Models',
);

$this->menu=array(
	array('label'=>'Create InformationModel', 'url'=>array('create')),
	array('label'=>'Manage InformationModel', 'url'=>array('admin')),
);
?>

<h1>Information Models</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

src/protected/views/information/update.php
<?php
/* @var $this InformationController */
/* @var $model InformationModel */

$this->breadcrumbs=array();

$this->menu=array();
?>

<h1>お知らせ編集</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

src/protected/views/information/view.php
<?php
/* @var $this InformationController */
/* @var $model InformationModel */

$this->breadcrumbs=array(
	'Information Models'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List InformationModel', 'url'=>array('index')),
	array('label'=>'Create InformationModel', 'url'=>array('create')),
	array('label'=>'Update InformationModel', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete InformationModel', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage InformationModel', 'url'=>array('admin')),
);
?>

<h1>View InformationModel #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'subject',
		'create_date',
		'update_date',
		'display_date',
		'begin_date',
		'end_date',
		'open_status',
		'description',
		'contents',
	),
)); ?>